import React, { useState } from 'react';
import { View, Text, FlatList, TouchableOpacity, Image, Modal, TouchableWithoutFeedback } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';
import { LinearGradient } from 'expo-linear-gradient';
import { useAvatarStore } from '../store/avatarStore';

// Mock Data for Chat List
const MOCK_CHATS = [
  {
    id: '1',
    name: 'AI 친구',
    lastMessage: '오늘 기분은 어떠신가요?',
    time: '방금 전',
    unread: 0,
    isMain: true, // The main avatar generated by user
  }
];

export default function ChatListScreen() {
  const navigation = useNavigation<any>();
  const { generatedAvatarUrl } = useAvatarStore();
  const [isMenuVisible, setMenuVisible] = useState(false);

  const renderItem = ({ item }: { item: typeof MOCK_CHATS[0] }) => (
    <TouchableOpacity 
      onPress={() => navigation.navigate('ChatDetail', { name: item.name, id: item.id })}
      className="flex-row items-center px-4 py-4 border-b border-white/5 active:bg-white/5"
    >
      {/* Avatar */}
      <View className="relative">
        <View className="w-14 h-14 rounded-full bg-gray-800 overflow-hidden border border-white/10 items-center justify-center">
          {item.isMain && generatedAvatarUrl ? (
             <Image source={{ uri: generatedAvatarUrl }} className="w-full h-full" resizeMode="cover" />
          ) : item.isMain ? (
             <Ionicons name="person" size={24} color="gray" />
          ) : (
             <Image source={{ uri: item.avatar }} className="w-full h-full" />
          )}
        </View>
        {item.id === '1' && (
            <View className="absolute bottom-0 right-0 w-4 h-4 bg-green-500 rounded-full border-2 border-black" />
        )}
      </View>

      {/* Content */}
      <View className="flex-1 ml-4">
        <View className="flex-row justify-between items-center mb-1">
          <Text className="text-white font-bold text-base">{item.name}</Text>
          <Text className="text-gray-500 text-xs">{item.time}</Text>
        </View>
        <Text className="text-gray-400 text-sm" numberOfLines={1}>
          {item.lastMessage}
        </Text>
      </View>

      {/* Unread Badge */}
      {item.unread > 0 && (
        <View className="ml-2 bg-pink-500 w-5 h-5 rounded-full items-center justify-center">
          <Text className="text-white text-[10px] font-bold">{item.unread}</Text>
        </View>
      )}
    </TouchableOpacity>
  );

  return (
    <View className="flex-1 bg-black">
       {/* Background Gradient */}
       <LinearGradient
          colors={['#000000', '#1a1a2e']}
          className="absolute inset-0 w-full h-full"
       />

      <SafeAreaView className="flex-1" edges={['top']}>
        {/* Header */}
        <View className="px-4 py-4 flex-row justify-between items-center z-50">
          <Text className="text-white text-2xl font-bold">대화</Text>
          <View className="flex-row gap-4 relative">
            <TouchableOpacity>
                <Ionicons name="search" size={24} color="white" />
            </TouchableOpacity>
            <TouchableOpacity onPress={() => setMenuVisible(true)}>
                <Ionicons name="add-circle-outline" size={28} color="white" />
            </TouchableOpacity>
          </View>
        </View>

        {/* Dropdown Menu Modal */}
        <Modal
          visible={isMenuVisible}
          transparent={true}
          animationType="fade"
          onRequestClose={() => setMenuVisible(false)}
        >
          <TouchableOpacity 
            className="flex-1 bg-black/50" 
            activeOpacity={1} 
            onPress={() => setMenuVisible(false)}
          >
             <View className="absolute top-[120px] right-4 bg-[#1E1E1E] rounded-2xl p-2 w-56 border border-white/10 shadow-xl">
                {/* Stop propagation when clicking inside menu */}
                <TouchableWithoutFeedback>
                  <View>
                    {/* Option 1: Story Mode */}
                    <TouchableOpacity 
                        className="flex-row items-center p-3 rounded-xl active:bg-white/10"
                        onPress={() => {
                          console.log("Navigating to StoryList");
                          setMenuVisible(false);
                          setTimeout(() => {
                            navigation.navigate('StoryList');
                          }, 100);
                        }}
                    >
                        <Ionicons name="book-outline" size={22} color="white" className="mr-3" />
                        <Text className="text-white font-medium ml-3">스토리 모드</Text>
                    </TouchableOpacity>

                    {/* Option 2: Chat Mode */}
                    <TouchableOpacity 
                        className="flex-row items-center p-3 rounded-xl active:bg-white/10"
                        onPress={() => {
                          setMenuVisible(false);
                          // Already in Chat Mode list, maybe create new chat?
                        }}
                    >
                        <Ionicons name="chatbubble-ellipses-outline" size={22} color="white" className="mr-3" />
                        <Text className="text-white font-medium ml-3">채팅 모드</Text>
                    </TouchableOpacity>
                  </View>
                </TouchableWithoutFeedback>
             </View>
          </TouchableOpacity>
        </Modal>

        {/* List */}
        <FlatList
          data={MOCK_CHATS}
          keyExtractor={item => item.id}
          renderItem={renderItem}
          contentContainerStyle={{ paddingBottom: 20 }}
        />
      </SafeAreaView>
    </View>
  );
}

